# Generated by Django 2.2.2 on 2021-04-17 12:24

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('url', models.URLField(max_length=400)),
                ('phone', phone_field.models.PhoneField(max_length=31, unique=True)),
            ],
        ),
    ]
